apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq-rs
  namespace: wachofi-ouali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        soft: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        ports:
          - containerPort: 5672  # AMQP protocol
          - containerPort: 15672 # Management UI
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"
          - name: RABBITMQ_DEFAULT_PASS
            value: "guest"
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
