apiVersion: v1
kind: Namespace
metadata:
  name: wachofi-ouali
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-rs
  namespace: wachofi-ouali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        soft: python
    spec:
      containers:
      - name: backend
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-2024:wachofi-ouali
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
