apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  namespace: wachofi-ouali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/front-image:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
