apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/redis-2024:wachofi-ouali
          ports:
            - containerPort: 6379
